### ISSUE TITLE
没用，一加6T Android 10

### ISSUE THREAD

**Issue by 62218** [twiceyuan/WXAPK#5]

**Comment by twiceyuan** [comment]
请问具体现象是？

我自己设备也是 Android 10，刚试了下试了下确实有些 apk 会提示“暂时无法打开”（比如这个 app 本身的 apk），但其他的就可以，不清楚是不是微信额外有一些判断策略。

如果不是这种现象，希望能提供更多信息

**Comment by twiceyuan** [comment]
无更多信息提供，暂时关闭
