### ISSUE TITLE
能否适配QQ

### ISSUE THREAD

**Issue by suqiernb** [twiceyuan/WXAPK#8]
* 最近QQ文件也将 `apk` 文件上传为了 `apk.1`
* QQ里面没有使用本软件打开的选项

**Comment by ipcjs** [comment]
你发issue太慢了，昨天已经适配了😂

**Comment by twiceyuan** [comment]
可以从 release 中下载 [1.10](https://github.com/twiceyuan/WXAPK/releases/tag/1.10) 版本。Play 版本因申请 REQUEST_INSTALL_PACKAGES 被下架了，短时间内不会恢复。

**Comment by tumuyan** [comment]
@twiceyuan  现在qq也能用，能否修改下这个应用名称、图标和说明？
